name: hetu_script_flutter_example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # hetu_script: "^0.4.2+1"
  hetu_script:
    path: ../../hetu_script
  # hetu_script_flutter: "^0.1.0+2"
  hetu_script_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - scripts/
    - scripts/hello/
